[package]
name = "streaming-geoparquet-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb = "0.10.1"
rocket = "0.5.0"
thiserror = "1.0.59"
